In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)

Array created:
 [[1 2 4]
 [5 8 7]]


In [2]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6S:\n",c)

Array with all 6S:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
#creating an array with random values
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.89188955 0.52052029]
 [0.4506864  0.15404097]]


In [10]:
#create a sequence of integers from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [18]:
#Reshaping 3×4 array to 2×2×3 array
import numpy as np
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,6]])
newarr = arr.reshape(4, 3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 6]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 6]]


In [20]:
# flatten array
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("\nFlattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 6]]

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 6]


In [30]:
arr = np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])
print("\nNo of dimensions:\n", arr.ndim)
print("\nShape of array:\n", arr.size)
print("\nSize of array:\n", arr.shape)
print("\nArray type:\n", arr.dtype)
newtype = arr.astype(np.float32)
print("\nConverted array elements:\n", newtype)
print("\nConverted array type:\n", newtype.dtype)




No of dimensions:
 2

Shape of array:
 12

Size of array:
 (3, 4)

Array type:
 int64

Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [2]:
import numpy as np
p = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("p[3:0:-1] ->", p[3:0:-1])   
print("p[2:0:2] ->", p[2:0:2])     
print("p[2:2:] ->", p[2:2:])      
print("p[3:3:] ->", p[3:3:])       
print("p[:1] ->", p[:1])          
c = p.astype('f')
print("\nConverted array elements (float):\n", c)

p[3:0:-1] -> [4 3 2]
p[2:0:2] -> []
p[2:2:] -> []
p[3:3:] -> []
p[:1] -> [1]

Converted array elements (float):
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
