In [2]:
import numpy as np
arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2]
])
print("Original array:\n", arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [4]:
#returns every other row
print("\nEvery other rows:\n",arr[0:3:2])


Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [6]:
#return every other element from the entire array
arr=np.array([1,2,3,4,5,6,7])
print("\n Original array:",arr)
print("\n Returns every other array [::2] \n",arr[::2])


 Original array: [1 2 3 4 5 6 7]

 Returns every other array [::2] 
 [1 3 5 7]


In [10]:
#slicing array
arr = np.array([
    [-1, 2, 0.4],
    [4, -0.5, 6.0],
    [2.6, 0, 7.0],
    [3, -7, 4.0]
])
temp = arr[:2, :3]
print("\nArray with first 2 rows and 3 columns:\n", temp)


Array with first 2 rows and 3 columns:
 [[-1.   2.   0.4]
 [ 4.  -0.5  6. ]]


In [20]:
#Integer array indexing
x = arr[[0, 1, 2, 3], [2, 2, 1, 0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):", x)


Elements at indices (0,3),(1,2),(2,1),(3,0): [ 3  6  8 10]


In [21]:
#boolean array indices
cond=arr>2
temp=arr[cond]
print("\n Elements greater than 2:\n",temp)


 Elements greater than 2:
 [ 3  4  5  6  7  8  9 10 11 12]


In [22]:
import numpy as np
#joining two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [23]:
#Horizontal join
arr3=np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [24]:
#vertical join
arr4=np.vstack((arr1,arr2))
print(arr4)

[[1 2 3]
 [4 5 6]]


In [25]:
#Depth join
arr5=np.dstack((arr1,arr2))
print(arr5)

[[[1 4]
  [2 5]
  [3 6]]]


In [26]:
#splitting of array
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
print(arr6[0])
