In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [2]:
#indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [6]:
#sorting the array
arr=np.array([3,2,0,1])
print("\n original array:",arr)
print("\n sorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\n original array",arr)
print("\n sorted array",np.sort(arr))


 original array: [3 2 0 1]

 sorted array: [0 1 2 3]

 original array [[3 2 4]
 [5 0 1]]

 sorted array [[2 3 4]
 [0 1 5]]
